'use client';
import React from 'react';
import { motion } from 'framer-motion';
import { Sparkles, Plane, X } from 'lucide-react';

interface FinalAnswerPanelProps {
  answer: string;
  source?: 'llm' | 'local';
  confidence?: number;
  onClose?: () => void;
}

function renderAnswer(text: string) {
  // Convert **bold**, ✈️ emojis, and newlines to JSX
  const lines = text.split('\n').filter(Boolean);
  return lines.map((line, i) => {
    const parts = line.split(/(\*\*[^*]+\*\*)/g);
    return (
      <p key={i} className="leading-relaxed mb-2 last:mb-0">
        {parts.map((part, j) => {
          if (part.startsWith('**') && part.endsWith('**')) {
            return <strong key={j} className="text-white font-bold">{part.slice(2, -2)}</strong>;
          }
          return <span key={j}>{part}</span>;
        })}
      </p>
    );
  });
}

export function FinalAnswerPanel({ answer, source, confidence, onClose }: FinalAnswerPanelProps) {
  if (!answer) return null;

  return (
    <motion.div
      initial={{ opacity: 0, y: -12, scale: 0.98 }}
      animate={{ opacity: 1, y: 0, scale: 1 }}
      exit={{ opacity: 0, y: -20, scale: 0.95 }}
      transition={{ duration: 0.4, ease: 'easeOut' }}
      className="mx-6 mb-0 mt-4 rounded-2xl border border-indigo-500/30 bg-gradient-to-br from-indigo-950/70 via-purple-950/50 to-black/60 backdrop-blur-md shadow-2xl shadow-indigo-900/30 overflow-hidden relative group"
    >
      {/* Header */}
      <div className="flex items-center gap-3 px-6 py-4 border-b border-indigo-500/20 bg-indigo-950/30">
        <div className="p-1.5 rounded-lg bg-indigo-500/20 border border-indigo-400/30">
          <Sparkles className="w-4 h-4 text-indigo-300" />
        </div>
        <div className="flex-1">
          <h3 className="text-sm font-bold text-indigo-200 tracking-wide">Agent Final Answer</h3>
          <p className="text-xs text-indigo-400/70">
            {source === 'llm' ? 'Generated by Gemini' : 'Synthesized locally'} 
            {confidence != null && ` · ${Math.round(confidence * 100)}% confidence`}
          </p>
        </div>
        <div className="flex items-center gap-3">
          <div className="flex items-center gap-2 pr-2 border-r border-white/10">
            <div className="w-2 h-2 rounded-full bg-green-400 animate-pulse" />
            <span className="text-[10px] text-green-400 font-bold uppercase tracking-wider">Complete</span>
          </div>
          
          {onClose && (
            <button 
              onClick={onClose}
              className="p-1.5 rounded-lg hover:bg-white/10 text-indigo-300 hover:text-white transition-all active:scale-95"
              aria-label="Dismiss"
            >
              <X className="w-4 h-4" />
            </button>
          )}
        </div>
      </div>

      {/* Answer body */}
      <div className="px-6 py-5 flex gap-4">
        <div className="mt-0.5 p-2 rounded-xl bg-gradient-to-br from-indigo-500/20 to-purple-500/20 border border-indigo-400/20 flex-shrink-0">
          <Plane className="w-5 h-5 text-indigo-300" />
        </div>
        <div className="text-sm text-indigo-100/90 font-medium">
          {renderAnswer(answer)}
        </div>
      </div>
    </motion.div>
  );
}
